let a;
console.log("Before Assignment: ",typeof a);
a = 1;
console.log("After Assignment: ",typeof a);
const aConst;
console.log("Before Assignment: ",typeof aConst);
aConst = 1;
console.log("After Assignment: ",typeof a);
let s;
console.log("Before Assignment: ",typeof s);
s = "string";
console.log("After Assignment: ",typeof s);
const sConst;
console.log("Before Assignment: ",typeof sConst);
sConst = "string";
console.log("After Assignment: ",typeof sConst);
let b;
console.log("Before Assignment: ",typeof b);
b=true;
console.log("After Assignment: ",typeof b);
const bConst;
console.log("Before Assignment: ",typeof bConst);
bConst = true;
console.log("After Assignment: ",typeof bConst);
let arr;
console.log("Before Assignment: ",typeof arr);
arr = [];
console.log("After Assignment: ",typeof arr);
const arrConst;
console.log("Before Assignment: ",typeof arrConst);
arrConst = [];
console.log("After Assignment: ",typeof arrConst);

